name: InfiniteStorageChests
version: 1.0.0
main: com.flowey258.infinitestoragechests.InfiniteStorageChests
api-version: 1.21
description: Adds craftable chests with infinite storage capacity
author: flowey258

commands:
  infinitechest:
    description: Main command for InfiniteStorageChests
    usage: /<command> [subcommand]
    aliases: [ichest, infchest]

permissions:
  infinitechest.use:
    description: Allows players to use Infinite Storage Chests
    default: true
  infinitechest.craft:
    description: Allows players to craft Infinite Storage Chests
    default: true
  infinitechest.admin:
    description: Gives access to all admin commands
    default: op
    children:
      infinitechest.use: true
      infinitechest.craft: true